export let stadiums = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [27.9419609, -26.2982244],
      },
      properties: {
        club: 'Orlando Pirates',
        code: 'os',
        stadium: 'Orlando Stadium',
        capacity: 40000,
        spactators: 241000,
        average: 16067,
        matches: 15,
        sold_out: '-',
        percentage: '40%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [27.981485, -26.234867],
      },
      properties: {
        club: 'Kaizer Chiefs',
        code: 'fnb',
        stadium: 'FNB Stadium',
        capacity: 94700,
        spactators: 223095,
        average: 17161,
        matches: 13,
        sold_out: '-',
        percentage: '18%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [30.462028, -22.98552],
      },
      properties: {
        club: 'Black Leopards FC',
        code: 'ts',
        stadium: 'Thohoyandou Stadium',
        capacity: 20000,
        spactators: 165742,
        average: 11049,
        matches: 15,
        sold_out: '-',
        percentage: '55%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [26.2310232, -29.1740833],
      },
      properties: {
        club: 'Bloemfontein Celtic',
        code: 'pm',
        stadium: 'Dr Petrus Molemela Stadium',
        capacity: 22000,
        spactators: 149657,
        average: 10690,
        matches: 14,
        sold_out: '-',
        percentage: '49%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [28.222435, -25.753229],
      },
      properties: {
        club: 'Mamelodi Sundowns FC',
        code: 'lv',
        stadium: 'Loftus Versfeld Stadium',
        capacity: 51762,
        spactators: 126400,
        average: 8427,
        matches: 15,
        sold_out: '-',
        percentage: '16%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [18.4076564, -33.904791],
      },
      properties: {
        club: 'Cape Town City FC',
        code: 'ct',
        stadium: 'Cape Town Stadium',
        capacity: 55000,
        spactators: 124600,
        average: 8307,
        matches: 15,
        sold_out: '1',
        percentage: '15%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [30.3862733, -29.6174467],
      },
      properties: {
        club: 'Maritzburg United FC',
        code: 'hg',
        stadium: 'Harry Gwala Stadium',
        capacity: 12000,
        spactators: 110700,
        average: 7380,
        matches: 15,
        sold_out: '-',
        percentage: '62%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [25.598555, -33.937717],
      },
      properties: {
        club: 'Chippa United',
        code: 'nm',
        stadium: 'Nelson Mandela Bay Stadium',
        capacity: 46000,
        spactators: 106003,
        average: 7067,
        matches: 15,
        sold_out: '-',
        percentage: '15%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [31.03027778, -29.82944444],
      },
      properties: {
        club: 'AmaZulu FC',
        code: 'kp',
        stadium: 'Kings Park Soccer Stadium',
        capacity: 55000,
        spactators: 86500,
        average: 5767,
        matches: 15,
        sold_out: '-',
        percentage: '10%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [29.4504011, -23.8980876],
      },
      properties: {
        club: 'Polokwane City FC',
        code: 'pms',
        stadium: 'Peter Mokaba Stadium',
        capacity: 46000,
        spactators: 79594,
        average: 5306,
        matches: 15,
        sold_out: '-',
        percentage: '12%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [27.9170773, -25.9747742],
      },
      properties: {
        club: 'SuperSport United',
        code: 'lm',
        stadium: 'Lucas Masterpieces Moripe Stadium',
        capacity: 28900,
        spactators: 78287,
        average: 5219,
        matches: 15,
        sold_out: '-',
        percentage: '18%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [28.2280216, -25.9990993],
      },
      properties: {
        club: 'Highlands Park FC',
        code: 'ma',
        stadium: 'Makhulong Stadium',
        capacity: 10000,
        spactators: 75300,
        average: 5020,
        matches: 15,
        sold_out: '-',
        percentage: '50%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [29.4504011, -23.8980876],
      },
      properties: {
        club: 'Baroka FC',
        code: 'pms',
        stadium: 'Peter Mokaba Stadium',
        capacity: 46000,
        spactators: 68926,
        average: 4595,
        matches: 15,
        sold_out: '-',
        percentage: '10%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [28.3026247, -28.2317702],
      },
      properties: {
        club: 'Free State Stars',
        code: 'gp',
        stadium: 'Goble Park',
        capacity: 5000,
        spactators: 38550,
        average: 2570,
        matches: 15,
        sold_out: '-',
        percentage: '51%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [30.8938693, -29.801679],
      },
      properties: {
        club: 'Lamontville Golden Arrows',
        code: 'sr',
        stadium: 'Sugar Ray Xulu Stadium',
        capacity: 6500,
        spactators: 37100,
        average: 2473,
        matches: 15,
        sold_out: '-',
        percentage: '38%',
      },
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [28.0303184, -26.1906216],
      },
      properties: {
        club: 'Bidvest Wits FC',
        code: 'bs',
        stadium: 'Bidvest Stadium',
        capacity: 15000,
        spactators: 36550,
        average: 2437,
        matches: 15,
        sold_out: '-',
        percentage: '16%',
      },
    },
  ],
}
